server:
  port: 7979

spring:
  application:
    name: shopcloud-gateway

swagger:
  title: shopcloud-gateway
  description: shopcloud-gateway


eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@123.207.121.33:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}


# 关闭权限验证
management:
  security:
    enabled: false