server:
  port: 8081

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

    #配置应用名字 不配置则默认：bootstrap
    #log目录、注册到eureka的名字
application:
    name: shopcloud-account

spring:
  datasource:
    druid:
      max-active: 20
      min-idle: 5
      initial-size: 1
      max-wait: 60000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: select 1 from dual
      pool-prepared-statements: false
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        enabled: true

      web-stat-filter:
        enabled: true
    url: jdbc:mysql://118.89.173.110:3306/sinoeshop?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: MyNewPass4!


#redis配置

  redis:
    host: 119.29.110.193
    port: 6379
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password: 123abc
    # 连接池最大连接数（使用负值表示没有限制）
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0