server:
  port: 8081

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false


spring:
  datasource:
    druid:
      max-active: 20
      min-idle: 5
      initial-size: 1
      max-wait: 60000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: select 1 from dual
      pool-prepared-statements: false
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        enabled: true

      web-stat-filter:
        enabled: true
    url: jdbc:mysql://118.89.173.110:3306/sinoeshop?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: MyNewPass4!
